<?php
$breakpoint = ! empty($settings->mobile_breakpoint) ? intval($settings->mobile_breakpoint) : 768;
$stack      = ! empty($settings->stack_mobile) ? $settings->stack_mobile : 'yes';
$layout     = $settings->menu_layout;
$show_sep   = ! empty($settings->show_separators) && 'yes' === $settings->show_separators;

// Spacing
$h_spacing = isset($settings->item_spacing) ? intval($settings->item_spacing) : 20;
$v_spacing = isset($settings->item_spacing_v) ? intval($settings->item_spacing_v) : 8;

// Alignment
$align_map = array('left' => 'start', 'center' => 'center', 'right' => 'end');
$flex_pos  = isset($align_map[$settings->menu_align]) ? $align_map[$settings->menu_align] : 'start';
?>

/* ── Nav container ───────────────────────────────────── */
.fl-node-<?php echo $id; ?> .wsbb-menu-nav {
<?php if (! empty($settings->menu_bg)) : ?>
  background-color: <?php echo FLBuilderColor::hex_or_rgb($settings->menu_bg); ?>;
<?php endif; ?>
<?php if (! empty($settings->menu_padding)) : ?>
  padding: <?php echo esc_attr($settings->menu_padding); ?>;
<?php endif; ?>
}

<?php if (! empty($settings->menu_align)) : ?>
  .fl-node-<?php echo $id; ?> .wsbb-menu-nav { text-align: <?php echo esc_attr($settings->menu_align); ?>; }
  <?php if ('horizontal' === $layout) : ?>
    .fl-node-<?php echo $id; ?> .wsbb-menu-list { justify-content: flex-<?php echo $flex_pos; ?>; }
  <?php endif; ?>
<?php endif; ?>

/* ── Links ───────────────────────────────────────────── */
.fl-node-<?php echo $id; ?> .wsbb-menu-nav a {
<?php if (! empty($settings->link_color)) : ?>
  color: <?php echo FLBuilderColor::hex_or_rgb($settings->link_color); ?>;
<?php endif; ?>
<?php if (! empty($settings->menu_font) && ! empty($settings->menu_font['family']) && 'Default' !== $settings->menu_font['family']) : ?>
  font-family: <?php echo esc_attr($settings->menu_font['family']); ?>;
<?php endif; ?>
<?php if (! empty($settings->menu_font) && ! empty($settings->menu_font['weight'])) : ?>
  font-weight: <?php echo esc_attr($settings->menu_font['weight']); ?>;
<?php endif; ?>
<?php if (! empty($settings->font_size)) : ?>
  font-size: <?php echo esc_attr($settings->font_size); ?>px;
<?php endif; ?>
<?php if (! empty($settings->letter_spacing)) : ?>
  letter-spacing: <?php echo esc_attr($settings->letter_spacing); ?>px;
<?php endif; ?>
<?php if (! empty($settings->text_transform)) : ?>
  text-transform: <?php echo esc_attr($settings->text_transform); ?>;
<?php endif; ?>
<?php if (isset($settings->link_padding_h)) : ?>
  padding-left: <?php echo esc_attr($settings->link_padding_h); ?>px;
  padding-right: <?php echo esc_attr($settings->link_padding_h); ?>px;
<?php endif; ?>
<?php if (isset($settings->link_padding_v)) : ?>
  padding-top: <?php echo esc_attr($settings->link_padding_v); ?>px;
  padding-bottom: <?php echo esc_attr($settings->link_padding_v); ?>px;
<?php endif; ?>
}

.fl-node-<?php echo $id; ?> .wsbb-menu-nav a:hover,
.fl-node-<?php echo $id; ?> .wsbb-menu-nav a:focus {
<?php if (! empty($settings->link_hover_color)) : ?>
  color: <?php echo FLBuilderColor::hex_or_rgb($settings->link_hover_color); ?>;
<?php endif; ?>
<?php if (! empty($settings->link_hover_bg)) : ?>
  background-color: <?php echo FLBuilderColor::hex_or_rgb($settings->link_hover_bg); ?>;
<?php endif; ?>
}

.fl-node-<?php echo $id; ?> .wsbb-menu-nav .current-menu-item > a,
.fl-node-<?php echo $id; ?> .wsbb-menu-nav .current_page_item > a {
<?php if (! empty($settings->link_active_color)) : ?>
  color: <?php echo FLBuilderColor::hex_or_rgb($settings->link_active_color); ?>;
<?php endif; ?>
}

<?php if (! empty($settings->font_size_medium)) : ?>
  @media ( max-width: 992px ) {
  .fl-node-<?php echo $id; ?> .wsbb-menu-nav a { font-size: <?php echo esc_attr($settings->font_size_medium); ?>px; }
  }
<?php endif; ?>

<?php if (! empty($settings->font_size_responsive)) : ?>
  @media ( max-width: 600px ) {
  .fl-node-<?php echo $id; ?> .wsbb-menu-nav a { font-size: <?php echo esc_attr($settings->font_size_responsive); ?>px; }
  }
<?php endif; ?>

/* ── Submenu toggle button (generated by walker) ────── */
.fl-node-<?php echo $id; ?> .wsbb-menu-nav .wsbb-has-submenu-container {
display: grid;
grid-template-columns: 1fr 40px;
position: relative;
}
.fl-node-<?php echo $id; ?> .wsbb-menu-nav .wsbb-submenu-toggle {
all: unset;
position: relative;
cursor: pointer;
display: flex;
align-items: center;
justify-content: center;
}
.fl-node-<?php echo $id; ?> .wsbb-menu-nav .wsbb-submenu-toggle::after {
content: '';
display: block;
width: 8px;
height: 8px;
border-right: 2px solid currentColor;
border-bottom: 2px solid currentColor;
transform: rotate(45deg);
transition: transform 0.2s;
}

/* Toggle arrow rotation when submenu is open */
.fl-node-<?php echo $id; ?> .wsbb-menu-nav .wsbb-has-submenu.wsbb-submenu-open > .wsbb-has-submenu-container .wsbb-submenu-toggle::after,
.fl-node-<?php echo $id; ?> .wsbb-menu-nav .wsbb-has-submenu:hover > .wsbb-has-submenu-container .wsbb-submenu-toggle::after {
transform: rotate(-135deg);
}

/* Plus icon style */
.fl-node-<?php echo $id; ?> .wsbb-menu-nav .wsbb-submenu-icon-plus .wsbb-submenu-toggle::after {
content: '+';
border: none;
width: auto;
height: auto;
font-size: 18px;
font-weight: 700;
transform: none;
}
.fl-node-<?php echo $id; ?> .wsbb-menu-nav .wsbb-submenu-icon-plus .wsbb-has-submenu.wsbb-submenu-open > .wsbb-has-submenu-container .wsbb-submenu-toggle::after {
content: '−';
}

/* No icon */
.fl-node-<?php echo $id; ?> .wsbb-menu-nav .wsbb-submenu-icon-none .wsbb-submenu-toggle {
display: none;
}

/* ── Spacing ─────────────────────────────────────────── */
<?php if ('horizontal' === $layout) : ?>
  .fl-node-<?php echo $id; ?> .wsbb-menu--horizontal .wsbb-menu-list > li {
  margin-right: <?php echo $h_spacing; ?>px;
  }
  .fl-node-<?php echo $id; ?> .wsbb-menu--horizontal .wsbb-menu-list > li:last-child {
  margin-right: 0;
  }
<?php endif; ?>

<?php if (in_array($layout, array('vertical', 'accordion'), true)) : ?>
  .fl-node-<?php echo $id; ?> .wsbb-menu--<?php echo $layout; ?> .wsbb-menu-list > li {
  margin-bottom: <?php echo $v_spacing; ?>px;
  }
<?php endif; ?>

/* ── Separators ──────────────────────────────────────── */
<?php if ($show_sep) : ?>
  .fl-node-<?php echo $id; ?> .wsbb-menu-list.wsbb-has-separators > li:not(:last-child)::after {
  border-color: <?php echo ! empty($settings->separator_color) ? FLBuilderColor::hex_or_rgb($settings->separator_color) : '#dadad3'; ?>;
  }
<?php endif; ?>

/* ── Dropdown ────────────────────────────────────────── */
.fl-node-<?php echo $id; ?> .wsbb-menu-nav .sub-menu {
<?php if (! empty($settings->dropdown_bg)) : ?>
  background: <?php echo FLBuilderColor::hex_or_rgb($settings->dropdown_bg); ?>;
<?php endif; ?>
}
.fl-node-<?php echo $id; ?> .wsbb-menu-nav .sub-menu a {
<?php if (! empty($settings->dropdown_link_color)) : ?>
  color: <?php echo FLBuilderColor::hex_or_rgb($settings->dropdown_link_color); ?>;
<?php endif; ?>
}
.fl-node-<?php echo $id; ?> .wsbb-menu-nav .sub-menu a:hover {
<?php if (! empty($settings->dropdown_link_hover_color)) : ?>
  color: <?php echo FLBuilderColor::hex_or_rgb($settings->dropdown_link_hover_color); ?>;
<?php endif; ?>
<?php if (! empty($settings->dropdown_link_hover_bg)) : ?>
  background-color: <?php echo FLBuilderColor::hex_or_rgb($settings->dropdown_link_hover_bg); ?>;
<?php endif; ?>
}

/* ── Toggle ──────────────────────────────────────────── */
.fl-node-<?php echo $id; ?> .wsbb-menu-toggle {
<?php if (! empty($settings->toggle_color)) : ?>
  color: <?php echo FLBuilderColor::hex_or_rgb($settings->toggle_color); ?>;
<?php endif; ?>
}
.fl-node-<?php echo $id; ?> .wsbb-menu-toggle-icon span {
<?php if (! empty($settings->toggle_color)) : ?>
  background: <?php echo FLBuilderColor::hex_or_rgb($settings->toggle_color); ?>;
<?php endif; ?>
}

/* ── Mobile ──────────────────────────────────────────── */
<?php if ('horizontal' === $layout && 'no' !== $stack) : ?>
  @media ( max-width: <?php echo $breakpoint; ?>px ) {
  .fl-node-<?php echo $id; ?> .wsbb-menu-toggle { display: inline-flex; }
  .fl-node-<?php echo $id; ?> .wsbb-menu-nav {
  display: none;
  <?php if (! empty($settings->mobile_menu_bg)) : ?>
    background: <?php echo FLBuilderColor::hex_or_rgb($settings->mobile_menu_bg); ?>;
  <?php endif; ?>
  padding: 12px 0;
  }
  .fl-node-<?php echo $id; ?> .wsbb-menu-nav.wsbb-menu--open { display: block; }
  .fl-node-<?php echo $id; ?> .wsbb-menu-list { flex-direction: column; }
  .fl-node-<?php echo $id; ?> .wsbb-menu-list > li {
  margin-right: 0 !important;
  margin-bottom: <?php echo $v_spacing; ?>px;
  }
  .fl-node-<?php echo $id; ?> .wsbb-menu-nav .sub-menu {
  position: static;
  box-shadow: none;
  padding-left: 16px;
  }
  }
<?php endif; ?>